HISTORY.md, README.md, lib/actions.js, lib/actions/duplicates.js, lib/actions/parse.js, lib/args.js, lib/models/bundle.js, lib/utils/code.js, package.json
* Add `--action=parse` report.
* Refactor args to better decompose actions.
* Update footer token removal for different webpack bundle types.
* Abstract `toParseable` utility.
There's a conspicuous note of needing a babel function to return `true` for matching multiple exports (which we define as a `module.exports` field that is set from a `require()` of another file -- it's not _just_ multiple fields on `module.exports`).
I've got a sample simple bundle up at: https://gist.github.com/ryan-roemer/c2b507ef0e17c392b9f09b7a03e1371c that you can use to testing things out.
```sh
$ bin/inspectpack.js \
--action=parse \
--bundle="/PATH/TO/bundle.multiple-exports.js" \
--format=text \
--suspect-parses
```
Feel free to commit directly to the `SUSPECT_PARSES.MULTIPLE_EXPORT` function, or branch my …
=> Add `--action=parse` report and misc fixes.

lib/actions/parse.js
This addition satisfies the simple case of ES6 import/export as outlined in #14.  It does track variables through `_interopRequireDefault`, which may catch the simple case of destructured imports also.  It will not track module references through intermediate variables, although it works around issues with double-exports of the same import module.
@ryan-roemer
=> Parse es6 import export

lib/actions/duplicates.js, lib/actions/files.js, lib/actions/parse.js, lib/actions/pattern.js, lib/actions/sizes.js, lib/actions/versions.js, lib/models/bundle.js
This is useful for processing in-memory Webpack bundles (say, for getting _real_ module sizes in `webpack-dashboard` 😃
=> Accept raw bundle strings in action options

lib/models/bundle.js
Webpack 2 adds extra comments for tracking module uses for tree-shaking, so the hardcoded line numbers resulted in code sections being treated as references. This decouples the header scraping from the line numbers.
=> Fix module header scraping for Webpack 2

.editorconfig, .eslintrc, bin/inspectpack.js, lib/actions.js, lib/actions/base.js, lib/actions/duplicates.js, lib/actions/files.js, lib/actions/parse.js, lib/actions/pattern.js, lib/actions/sizes.js, lib/actions/versions.js, lib/args.js, lib/daemon/index.js, lib/daemon/worker.js, lib/index.js, lib/models/bundle.js, lib/models/code.js, lib/utils/cache.js, lib/utils/code.js, lib/utils/compressor.js, lib/utils/data.js, lib/utils/hash.js, lib/utils/parser.js, package.json, test/.eslintrc, test/smoke.spec.js, yarn.lock
Depends on https://github.com/FormidableLabs/inspectpack/pull/26
This PR introduces a child process daemon mode for interactive usage (e.g. `webpack-dashboard`). Creating a daemon prevents `inspectpack` from blocking UI interactions and allows for future parallelization of action runners.
- Use `traverse.cheap` in the parser
- Remove all `gzipSync` in the `sizes` action for both daemon and CLI mode
- Add both an action-level and module-level in-memory + disk cache, making all builds except the first run cheaper
- Centralize file size gathering/caching into an injectable Compressor class
Todo:
=> Daemon mode with performance improvements

lib/actions/versions.js, lib/models/bundle.js, yarn.lock
The assumption at https://github.com/FormidableLabs/inspectpack/compare/bug/version-paths?expand=1#diff-55add4d0584840b5b138fedc70a2384eL248 didn't hold up for a test bundle. Since we already have the full path for the bundle, we can just `path.resolve` it with the root.
=> Use the bundle path to find relative location from root in versions

lib/utils/code.js
Addresses #34. 
When parsing bundles created with the devtool option set to `eval` a `//` comment proceeds the closing `}` of each module function which results in uglify parse errors. This fix ensures the closing bracket is on a new line.  Tested with all [devtool](https://webpack.js.org/configuration/devtool/#devtool) options listed 
/cc @ryan-roemer
=> Fix size inspection of bundles created with devtool: eval

HISTORY.md, README.md, lib/args.js, lib/models/bundle.js, lib/parser/extractors.js, lib/parser/matchers.js, package.json, test/lib/parser/extractors.spec.js, test/playbook.spec.js, test/smoke.spec.js, test/util.js, yarn.lock
I've added more tests using the `formidable-playbook` fixtures for more scenarios. There's still a lot more that we can do with those...
* Add `formidable-playbook` as fixtures.
* Add basic DLL tests
* Assert on module id parsing (and fix it).
* Handle a wide range of bad inputs on parser matches + test. Fixes FormidableLabs/electron-webpack-dashboard#10
* Add `allowEmpty` action option / `--allow-empty` CLI flag to not throw errors when passing in a minified bundle / bundle with `pathinfo` / anything `inspectpack` _can't_ parse. This is one option to enable and hopefully silence errors in FormidableLabs/electron-webpack-dashboard#1 although note that there will be no inspectpack stats. I have filed a future research issue to investigate using `stats.json` as an alternate path to …
=> Make code more resilient to unexpected inputs + moar tests.

lib/actions/duplicates.js, lib/utils/compressor.js, package.json, yarn.lock
This lets us handle webpack projects that use `uglify-es` (e.g. Node projects that bundle without transpilation)!
=> Upgrade to uglify-es

HISTORY.md, lib/parser/extractors.js, lib/utils/compressor.js, test/lib/parser/extractors.spec.js, test/lib/utils/compressor.spec.js
In working through FormidableLabs/webpack-dashboard#182 at a minimum, we have a bug where `inspectpack` removes all lines _after_ a `sourceMappingUrl` comment, which it should just remove the entire line and nothing after.
Changes:
- Add regression test for `sourceMappingUrl` over-truncation bug.
- Add more general tests for extractor and compressor
- Fix sourcemapping comment removal
- Refactor out unnecessary Promise.all in code.
- Better JS parsing errors from minifier.
/cc @tptee @kenwheeler
=> Bug: Fix bad sourcemaps parsing.

.gitignore, lib/daemon/index.js, lib/daemon/worker.js, lib/utils/cache.js, lib/utils/compressor.js, lib/utils/safe-json.js, package.json, test/smoke.spec.js, yarn.lock
This PR replaces the custom `Map`/file cache with a simple SQLite integration. This gives us a few things:
- No more overflushing to disk/indecision over when to flush to disk.
- It's safe to write concurrently to a SQLite database ([when in WAL mode](https://sqlite.org/wal.html)). This means we can use more than one worker–the worker pool now matches the number of CPUs.
Parallelizing the sizes and problems actions seems to boost performance around 2x, although I haven't measured it yet.
Breaking changes: the async class factories previously named `init` are now synchronous and named `create`.
=> Use sqlite to back cache and enable multiprocessing

.gitignore, lib/daemon/index.js, lib/daemon/worker.js, lib/models/bundle.js, lib/utils/cache.js, lib/utils/compressor.js, lib/utils/hash.js, package.json, test/.eslintrc, test/lib/utils/compressor.spec.js, test/smoke.spec.js, yarn.lock
* Make `better-sqlite3` and `optionalDependency`. Switch to noop cache if not present. Fixes #49
* Add `Cache.wrapAction` helper for common use case of "try cache get, do action, set cache".
* Change cross-process communication to just serialize/deserialize the applicable cache instance.
* Various refactoring and cleanup.
* Re-enabled eslint rules for better hamonized style.
* Add `cache` option for `InspectpackDaemon.create`.
* Add error logging for worker errors.
/cc @tptee @gartz
=> Optional cache + refactor.

lib/models/bundle.js, test/playbook.spec.js
* Handle weird `{ type: "Buffer", data: [INTEGERS] }` plain JavaScript object by detecting and converting it manually to a real `Buffer` object, then string. Fixes https://github.com/FormidableLabs/webpack-dashboard/issues/193
@jpduckwo @servicelevel -- Can you try out this version of inspectpack to see if this solves your issues with `TypeError: this.input.charCodeAt is not a function` in `webpack-dashboard`?
/cc @tptee
=> Handle weird, quasi-buffer objects.

src/lib/actions/base.ts, src/lib/actions/versions.ts, test/fixtures/scoped/node_modules/bar/index.js, test/fixtures/scoped/node_modules/bar/package.json, test/fixtures/scoped/node_modules/bar/tender.js, test/fixtures/scoped/package.json, test/fixtures/scoped/src/index.js, test/lib/actions/base.spec.ts, test/lib/actions/sizes.spec.ts, test/lib/actions/versions.spec.ts
Originally, a simple `substr` of the `identifier` (unprocessed) from the (processed) `baseName` was used to slice off the part of a full path to a node_modules file. This ended up with incorrect paths to modules.
Now, we actually split then rejoin the path more reliably.
Also adds some test fixtures and does some futzing to baseName for synthetic modules.
=> Bug: fix path to package inference

.travis.yml, appveyor.yml, package.json, test/lib/actions/versions.spec.ts, yarn.lock
- Add missing `package.json:bin` entry. Fixes #81 
- Update travis config to not do `node@10.5+`. See #83
=> BUG: package.json:bin is missing.

HISTORY.md, README.md, src/plugin/duplicates.ts, test/lib/plugin/duplicates.spec.ts
Allows us to actually get output on next / builds that totally wrap webpack:
```js
new DuplicatesPlugin({
verbose: true,
emitHandler: (report) => {
console.log(report);
}
})
```
/cc @tptee
=> Add `emitHandler` option to `DuplicatesPlugin` to allow customized output

HISTORY.md, README.md, src/lib/actions/base.ts, test/lib/actions/base.spec.ts
Part of #79
- BUG: A loader in the `identifier` field would incorrectly have all modules inferred "as a `node_modules` file", even if not. Implements a naive loader stripping heuristic to correctly assess if `node_modules` or real application source.
- Optimizes internal calls to `_isNodeModules()` from 2 to 1 for better performance.
=> BUG: Fix inference of node_modules for loader prefixes.

HISTORY.md, src/lib/actions/base.ts, src/lib/interfaces/webpack-stats.ts, test/lib/actions/base.spec.ts, test/lib/actions/sizes.spec.ts
- Use the `name` field to better normalize `identifier` and remove trailing stuff in `path.js 0`.
- Sets up using `_normalizeWebpackPath(identifier) === normalizedId;` to check if something is likely . generated / synthetic.
- **NOTE**:  Can have more `basePath` duplicates now (because loader stuff stripped).
=> BUG: more identifier normalization

HISTORY.md, README.md, src/lib/actions/base.ts, src/lib/actions/versions.ts, src/lib/util/dependencies.ts, src/lib/util/promise.ts, src/plugin/duplicates.ts, test/fixtures/config/scenarios.json, test/fixtures/hidden-app-roots/node_modules/different-foo/index.js, test/fixtures/hidden-app-roots/node_modules/different-foo/node_modules/foo/car.js, test/fixtures/hidden-app-roots/node_modules/different-foo/node_modules/foo/index.js, test/fixtures/hidden-app-roots/node_modules/different-foo/node_modules/foo/package.json, test/fixtures/hidden-app-roots/node_modules/different-foo/package.json, test/fixtures/hidden-app-roots/node_modules/foo/index.js, test/fixtures/hidden-app-roots/node_modules/foo/package.json, test/fixtures/hidden-app-roots/package.json, test/fixtures/hidden-app-roots/packages/hidden-app/package.json, test/fixtures/hidden-app-roots/packages/hidden-app/src/index.js, test/fixtures/hidden-app-roots/webpack.config.js, test/lib/actions/versions.spec.ts, test/lib/plugin/duplicates.spec.ts, test/lib/util/dependencies.spec.ts, test/lib/util/promise.spec.ts, test/utils.ts
Version 2. Supersedes #104 
When an application root has no actual `node_modules` in it, the `versions` action inference fails to find the app root `package.json` file and misses traversing the versions dependencies. This has the buggy effects of:
- Missing information in `versions` action for CLI
- Missing information in `DuplicatesPlugin`.
=> BUG: hidden app roots (v2)

HISTORY.md, src/lib/actions/base.ts, src/lib/interfaces/webpack-stats.ts, test/lib/actions/sizes.spec.ts
- Expand type to allow `null` and handle in code. Fixes #110 
- Add regression tests.
@westbrook-asapp - If you have a moment, want to try this one out? (No worries if not, I'm pretty sure this fixes the issue as your stats file now is parseable with this change. Thanks again so much for generating it -- it dramatically reduced the amount of time needed to fix this!)
/cc @parkerziegler
=> BUG: Handle null chunks in webpack stats object.

HISTORY.md, README.md, src/bin/lib/args.ts, src/lib/actions.ts, src/lib/actions/base.ts, src/plugin/duplicates.ts, test/fixtures/config/webpack.config.js, test/lib/plugin/duplicates.spec.ts
Building on @tido64's great work in #133 this adds a few extra things:
- Add `ignoredPackages` to core + plugin ( @tido64 )
- Add `--ignored-packages|-i` CLI option
- Add regex option
- Update docs
@tido64 -- Can you review and see if you're good with the additional changes? And maybe kick the tires on the PR to make sure it works for your use case? Thanks! 🙏
=> Feature: Add ignored packages option to plugin + CLI
